
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Blob;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JViewport;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BusquedaVentas.java
 *
 * Created on 20-abr-2011, 14:43:35
 */

/**
 *
 * @author Administrador
 */
public class BusquedaVentas extends javax.swing.JInternalFrame {

    VentanaPrincipal padre = new VentanaPrincipal();
    //Factura fact ;
    int llevaFila = 0;
    public static JTextField codigo;
    public static JTextField nombreProducto;
    ConectorMySQL conexion;
    public JTextField bodega, stock, precio, cantidadVenta;
    public JLabel imagen;
    public File fotografia2 = null;

    public BusquedaVentas(ConectorMySQL conectorMySql, JTextField nombreProducto, JTextField codigo, JTextField bodega, JTextField stock, JTextField precio, JLabel imagen, JTextField cantidadVenta) {
        this.codigo = codigo;
        this.cantidadVenta = cantidadVenta;
        this.imagen = imagen;
        this.nombreProducto = nombreProducto;
        this.conexion = conectorMySql;
        this.bodega = bodega;
        this.stock = stock;
        this.precio = precio;
        initComponents();
        


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTConsultas = new javax.swing.JTable();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jTConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion"
            }
        ));
        jTConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTConsultasMouseClicked(evt);
            }
        });
        jTConsultas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTConsultasKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTConsultas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    //METODO PARA DARLE UN TAMAÑO DESEADO A CADA COLUMNA DE LA TABLA
    public void setAnchoColumnas(JTable tabla){
        JViewport scroll =  (JViewport) tabla.getParent();
        int ancho = scroll.getWidth();
        int anchoColumna = 0;
        TableColumnModel modeloColumna = tabla.getColumnModel();
        TableColumn columnaTabla;
        for(int i = 0; i < tabla.getColumnCount(); i++){
            columnaTabla = modeloColumna.getColumn(i);
            switch(i){
                case 0: anchoColumna = 40; break;
                case 1: anchoColumna = 100; break;
            }
            columnaTabla.setPreferredWidth(anchoColumna);
        }
    }


    private void jTConsultasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTConsultasKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_F2){
            this.jTConsultas.grabFocus();
        }
        if(nombreProducto != null){
            codigo.setText(jTConsultas.getValueAt(jTConsultas.getSelectedRow(), 0).toString());
            nombreProducto.setText(jTConsultas.getValueAt(jTConsultas.getSelectedRow(), 1).toString());
        }
        setVisible(false);
    }//GEN-LAST:event_jTConsultasKeyPressed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
//        this.codigo.grabFocus();
//        this.repaint();
//        this.updateUI();
//        //luego de inicializar los componentes, consulto y muestro en la tabla
//        try{
//           int fila = 0;
//           String sql = "SELECT * FROM productos WHERE nombre LIKE '%"+nombreProducto.getText().toLowerCase()+"%' ";
//           ResultSet rs = conexion.sentencia.executeQuery(sql);
//           if(rs.next()){
//               this.jTConsultas.setValueAt(rs.getString("nombre"), fila, 1);
//               fila++;
//           }
//       }catch(Exception er){
//            JOptionPane.showMessageDialog(null, "error en keyTyped : "+er.toString());
//       }
    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        
    }//GEN-LAST:event_formInternalFrameClosing

    private void jTConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTConsultasMouseClicked
        if(nombreProducto != null){
            codigo.setText(jTConsultas.getValueAt(jTConsultas.getSelectedRow(), 0).toString());
            nombreProducto.setText(jTConsultas.getValueAt(jTConsultas.getSelectedRow(), 1).toString());
            //consulto en la base de datos para mostrar demas datos del producto
            try{
                String sql = "SELECT * FROM productos WHERE id = '"+jTConsultas.getValueAt(jTConsultas.getSelectedRow(), 0).toString()+"' ";
                ResultSet rs = conexion.sentencia.executeQuery(sql);
                if(rs.next()){
                    bodega.setText(rs.getString("cantidad"));
                    stock.setText(rs.getString("stock"));
                    precio.setText("$ "+rs.getString("precio_venta_unidad"));
                    cantidadVenta.setText("1");
                    //CARGO LA IMAGEN
                    Blob foto = rs.getBlob("imagen");
                    if(foto!=null){
                        byte[] byteHuella = foto.getBytes(1,(int)foto.length());
                        fotografia2 = new File("temp/" + rs.getString("id") + ".jpg");
                        FileOutputStream canalSalida = new FileOutputStream(fotografia2);
                        canalSalida.write(byteHuella);
                        canalSalida.close();
                        //MOSTRAR LA IMAGEN EN LA VISTA PREVIA
                        ImageIcon imagenFoto = new ImageIcon("temp/"+rs.getString("id") + ".jpg");
                        Image imageAuxiliar = imagenFoto.getImage();
                        imageAuxiliar = imageAuxiliar.getScaledInstance(imagen.getWidth(), imagen.getHeight(), Image.SCALE_AREA_AVERAGING);
                        imagenFoto.setImage(imageAuxiliar);
                        imagen.setIcon(imagenFoto);
                        imagen.updateUI();
                    }
                    
                }
            }catch(Exception er){
                JOptionPane.showMessageDialog(null, "error mostrando demas datos : "+er.toString());
            }
        }
        setVisible(false);
    }//GEN-LAST:event_jTConsultasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTConsultas;
    // End of variables declaration//GEN-END:variables

}
