
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Blob;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Busqueda2.java
 *
 * Created on 20-abr-2011, 14:43:35
 */

/**
 *
 * @author Administrador
 */
public class BusquedaAumentos extends javax.swing.JInternalFrame {

    VentanaPrincipal padre;
    JTextField producto;
    JButton boton;
    JTextField campoCantidad, precio_entrada, fechaEntrada, precioVentaUnidad, proveedor;
    JLabel textoCantidad, TextCantidadAdicionar, imagen;
    JTextField campoCantidadAdicionar, stock;
    File fotografia = null;
    
    public BusquedaAumentos(VentanaPrincipal padre, JLabel imagen, JTextField stock, JTextField campoCantidadAdicionar, JLabel TextCantidadAdicionar, JTextField producto, JButton boton, JLabel textoCantidad, JTextField campoCantidad, JTextField precio_entrada, JTextField fechaEntrada, JTextField precioVentaUnidad, JTextField proveedor) {
        initComponents();
        this.padre = padre;
        this.imagen = imagen;
        this.stock = stock;
        this.TextCantidadAdicionar = TextCantidadAdicionar;
        this.campoCantidadAdicionar = campoCantidadAdicionar;
        this.campoCantidad = campoCantidad;
        this.textoCantidad = textoCantidad;
        this.producto = producto;
        this.boton = boton;
        this.precio_entrada = precio_entrada;
        this.fechaEntrada = fechaEntrada;
        this.precioVentaUnidad = precioVentaUnidad;
        this.proveedor = proveedor;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTConsultas = new javax.swing.JTable();

        jTConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion"
            }
        ));
        jTConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTConsultasMouseClicked(evt);
            }
        });
        jTConsultas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTConsultasKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTConsultas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTConsultasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTConsultasKeyPressed
       
    }//GEN-LAST:event_jTConsultasKeyPressed

    private void jTConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTConsultasMouseClicked
        try{
            //ingreso en el campo del nombre el nombre escojido de la tabla
            Productos.jTCodigo.setText(jTConsultas.getValueAt(jTConsultas.getSelectedRow(), 0).toString());
            Productos.jTProducto.setText(jTConsultas.getValueAt(jTConsultas.getSelectedRow(), 1).toString());
            try{
                String sql = "SELECT * FROM productos WHERE id = '"+jTConsultas.getValueAt(jTConsultas.getSelectedRow(), 0).toString()+"'";
                ResultSet rs = padre.conectorMySql.sentencia.executeQuery(sql);
                if(rs.next()){
                    boton.setText("Actualizar");
                    campoCantidadAdicionar.setVisible(true);
                    TextCantidadAdicionar.setVisible(true);

                    precio_entrada.setText(rs.getString("precio_entrada"));
                    campoCantidad.setText(rs.getString("cantidad"));
                    fechaEntrada.setText(rs.getString("fecha_entrada"));
                    precioVentaUnidad.setText(rs.getString("precio_venta_unidad"));
                    proveedor.setText(rs.getString("proveedor").toUpperCase());
                    stock.setText(rs.getString("stock"));
                    Blob img = rs.getBlob("imagen");
                    if(img!=null){
                        imagen.setText("");
                        byte[] byteHuella = img.getBytes(1,(int)img.length());
                        fotografia = new File("temp/" + rs.getString("id") + ".jpg");
                        FileOutputStream canalSalida = new FileOutputStream(fotografia);
                        canalSalida.write(byteHuella);
                        canalSalida.close();
                        //MOSTRAR LA IMAGEN EN LA VISTA PREVIA
                        ImageIcon imagenFoto = new ImageIcon("temp/"+rs.getString("id") + ".jpg");
                        Image imageAuxiliar = imagenFoto.getImage();
                        imageAuxiliar = imageAuxiliar.getScaledInstance(imagen.getWidth(), imagen.getHeight(), Image.SCALE_AREA_AVERAGING);
                        imagenFoto.setImage(imageAuxiliar);
                        imagen.setIcon(imagenFoto);
                        imagen.updateUI();
                    }
                }
            }catch(Exception er){
                JOptionPane.showMessageDialog(null, "error llenando campos : "+er.toString());
            }
            Productos.jTProducto.grabFocus();
            dispose();
            
       }catch(Exception er){
            JOptionPane.showMessageDialog(null, "error colocando el texto en el campo : "+er.toString());
       }
    }//GEN-LAST:event_jTConsultasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTConsultas;
    // End of variables declaration//GEN-END:variables

}
