
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Blob;
import java.sql.ResultSet;
import java.util.Locale;
import java.util.Properties;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
//IMPORTAMOS PAQUETES PARA EL ENVIO DE CORREOS
import javax.mail.Message;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.InternetAddress;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Loguear.java
 *
 * Created on 26-abr-2011, 19:39:54
 */

/**
 *
 * @author Administrador
 */
public class Loguear extends javax.swing.JDialog {

    VentanaPrincipal padre;
    File fotografia2 = null;
    Random aleatorio = new Random();

    public Loguear(VentanaPrincipal padre, boolean modal) {
        super(padre, modal);
        this.padre = padre;
        initComponents();
        //jTCampoUsuario.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPCambiarContrasena = new javax.swing.JPanel();
        jLImagenEmpresaCambio = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPContrasenaActual = new javax.swing.JPasswordField();
        jLNuevaContrasena = new javax.swing.JLabel();
        jPContrasena1 = new javax.swing.JPasswordField();
        jLContrasenaOtraVez = new javax.swing.JLabel();
        jPContrasenaNuevamente = new javax.swing.JPasswordField();
        jPImagenUser = new javax.swing.JPanel();
        jLImagenUser = new javax.swing.JLabel();
        jBCargar = new javax.swing.JButton();
        jLAtras = new javax.swing.JLabel();
        jPRecuperarContrasena = new javax.swing.JPanel();
        jLImagen2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTDireccionEmail = new javax.swing.JTextField();
        jBEnviar = new javax.swing.JButton();
        jLAtras2 = new javax.swing.JLabel();
        jPGlobal = new javax.swing.JPanel();
        jPLoguearUsuario = new javax.swing.JPanel();
        jPPasswordField = new javax.swing.JPasswordField();
        jLImagenEmpresa = new javax.swing.JLabel();
        jPImagen = new javax.swing.JPanel();
        jLImagen = new javax.swing.JLabel();
        jLMensajeBienvenida = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTCampoUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLOlvideContrasena = new javax.swing.JLabel();
        jLCambiarContrasena = new javax.swing.JLabel();
        jLTextoBienvenida = new javax.swing.JLabel();

        jPCambiarContrasena.setBackground(new java.awt.Color(255, 255, 255));

        jLImagenEmpresaCambio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLImagenEmpresaCambio.setText("<html>Esta Interfaz te permite <B>Cambiar</b> tu Contraseña, para mayor siguridad del sistema y de tu Usuario, impidiendo que otra persona ingrese con tu usuario. </html>");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLabel4.setText("Ingrese Contraseña Actual :");

        jPContrasenaActual.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPContrasenaActual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPContrasenaActualKeyPressed(evt);
            }
        });

        jLNuevaContrasena.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLNuevaContrasena.setText("* Nueva Contraseña :");

        jPContrasena1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLContrasenaOtraVez.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLContrasenaOtraVez.setText("*  Contraseña Nuevamente :");

        jPContrasenaNuevamente.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jPImagenUser.setBackground(new java.awt.Color(255, 255, 255));
        jPImagenUser.setLayout(new java.awt.BorderLayout());

        jLImagenUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLImagenUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        jPImagenUser.add(jLImagenUser, java.awt.BorderLayout.CENTER);

        jBCargar.setText("Cargar");
        jBCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCargarActionPerformed(evt);
            }
        });

        jLAtras.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLAtras.setText("... Atras");
        jLAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLAtrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLAtrasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPCambiarContrasenaLayout = new javax.swing.GroupLayout(jPCambiarContrasena);
        jPCambiarContrasena.setLayout(jPCambiarContrasenaLayout);
        jPCambiarContrasenaLayout.setHorizontalGroup(
            jPCambiarContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCambiarContrasenaLayout.createSequentialGroup()
                .addGroup(jPCambiarContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCambiarContrasenaLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLAtras)
                        .addGap(76, 76, 76)
                        .addComponent(jBCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPCambiarContrasenaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPCambiarContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLImagenEmpresaCambio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPCambiarContrasenaLayout.createSequentialGroup()
                                .addGroup(jPCambiarContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLContrasenaOtraVez, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLNuevaContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPContrasenaActual)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPContrasena1)
                                    .addComponent(jPContrasenaNuevamente))
                                .addGap(42, 42, 42)
                                .addComponent(jPImagenUser, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPCambiarContrasenaLayout.setVerticalGroup(
            jPCambiarContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCambiarContrasenaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLImagenEmpresaCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPCambiarContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCambiarContrasenaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPContrasenaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLNuevaContrasena)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPContrasena1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLContrasenaOtraVez)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPContrasenaNuevamente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPImagenUser, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPCambiarContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLAtras)
                    .addComponent(jBCargar))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPRecuperarContrasena.setBackground(new java.awt.Color(255, 255, 255));

        jLImagen2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLImagen2.setText("<html>Esta Interfaz te permite <B>Recuperar</B> tu Contraseña, luego que se te olvide, y asi permitirte el ingreso al Sistema, luego de validar tus datos, y que ingreses la contraseña que te suinistra el Sistema.</html>");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingresa tu Direccion E_mail.");

        jTDireccionEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jBEnviar.setText("Enviar");
        jBEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEnviarActionPerformed(evt);
            }
        });

        jLAtras2.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLAtras2.setText("... Atras");
        jLAtras2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLAtras2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLAtras2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLAtras2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPRecuperarContrasenaLayout = new javax.swing.GroupLayout(jPRecuperarContrasena);
        jPRecuperarContrasena.setLayout(jPRecuperarContrasenaLayout);
        jPRecuperarContrasenaLayout.setHorizontalGroup(
            jPRecuperarContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRecuperarContrasenaLayout.createSequentialGroup()
                .addGroup(jPRecuperarContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPRecuperarContrasenaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPRecuperarContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                            .addComponent(jTDireccionEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                            .addComponent(jLImagen2, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)))
                    .addGroup(jPRecuperarContrasenaLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jBEnviar))
                    .addGroup(jPRecuperarContrasenaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLAtras2)))
                .addContainerGap())
        );
        jPRecuperarContrasenaLayout.setVerticalGroup(
            jPRecuperarContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRecuperarContrasenaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTDireccionEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBEnviar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jLAtras2)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("INGRESAR");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPGlobal.setBackground(new java.awt.Color(255, 255, 255));
        jPGlobal.setLayout(new java.awt.BorderLayout());

        jPLoguearUsuario.setBackground(new java.awt.Color(255, 255, 255));

        jPPasswordField.setFont(new java.awt.Font("Tahoma", 1, 11));
        jPPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPPasswordFieldKeyPressed(evt);
            }
        });

        jLImagenEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLImagenEmpresa.setText("Imagen");

        jPImagen.setBackground(new java.awt.Color(255, 255, 255));
        jPImagen.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPImagen.setLayout(new java.awt.BorderLayout());

        jLImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLImagen.setText("Imagen");
        jPImagen.add(jLImagen, java.awt.BorderLayout.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLabel2.setText("Usuario :");

        jTCampoUsuario.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTCampoUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTCampoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTCampoUsuarioKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLabel3.setText("Contraseña :");

        jLOlvideContrasena.setForeground(new java.awt.Color(255, 0, 0));
        jLOlvideContrasena.setText("Olvide mi Contraseña ");
        jLOlvideContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLOlvideContrasenaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLOlvideContrasenaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLOlvideContrasenaMouseExited(evt);
            }
        });

        jLCambiarContrasena.setForeground(new java.awt.Color(0, 0, 255));
        jLCambiarContrasena.setText("Cambiar mi Contraseña ");
        jLCambiarContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCambiarContrasenaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLCambiarContrasenaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLCambiarContrasenaMouseExited(evt);
            }
        });

        jLTextoBienvenida.setText("Bienvenido(a)");

        javax.swing.GroupLayout jPLoguearUsuarioLayout = new javax.swing.GroupLayout(jPLoguearUsuario);
        jPLoguearUsuario.setLayout(jPLoguearUsuarioLayout);
        jPLoguearUsuarioLayout.setHorizontalGroup(
            jPLoguearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLoguearUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPLoguearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLMensajeBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLOlvideContrasena)
                    .addComponent(jLCambiarContrasena)
                    .addGroup(jPLoguearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTCampoUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPPasswordField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                    .addComponent(jLTextoBienvenida)
                    .addComponent(jLImagenEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPLoguearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPLoguearUsuarioLayout.createSequentialGroup()
                    .addContainerGap(210, Short.MAX_VALUE)
                    .addComponent(jPImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPLoguearUsuarioLayout.setVerticalGroup(
            jPLoguearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLoguearUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLImagenEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTCampoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLOlvideContrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLCambiarContrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLTextoBienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLMensajeBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPLoguearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPLoguearUsuarioLayout.createSequentialGroup()
                    .addContainerGap(99, Short.MAX_VALUE)
                    .addComponent(jPImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPGlobal.add(jPLoguearUsuario, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPGlobal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTCampoUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTCampoUsuarioKeyPressed
        ingresarSistema(evt);
    }//GEN-LAST:event_jTCampoUsuarioKeyPressed

    //metodo para consultar y validar
    public void ingresarSistema(java.awt.event.KeyEvent evt){
        try{
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                if(!jTCampoUsuario.getText().isEmpty() && !jPPasswordField.getText().isEmpty()){
                    //String sql = "SELECT * FROM usuario WHERE password = '"+jPPasswordField.getText()+"' AND user = '"+jTCampoUsuario.getText().toLowerCase()+"' ";
                    String sql = "SELECT * FROM usuario WHERE user = '"+jTCampoUsuario.getText().toLowerCase()+"' ";
                    ResultSet rs = padre.conectorMySql.sentencia.executeQuery(sql);
                    if(rs.next()){
                        System.out.println("la contraseña es : "+rs.getString("password"));
                        padre.contrasena = rs.getString("password");
                        if(rs.getString("password").equals(jPPasswordField.getText())){
                            //atrapo el nombre del usuario actual de sistema
                            padre.perfil = rs.getString("perfil");
                            padre.usuario = rs.getString("Nombres");
                            jLMensajeBienvenida.setText("<html><b>"+rs.getString("nombres").toUpperCase()+"</b></html>");
                            jLMensajeBienvenida.setVisible(true);
                            //muestro la foto
                            Blob foto = rs.getBlob("foto");
                            if(foto!=null){
                                byte[] byteHuella = foto.getBytes(1,(int)foto.length());
                                fotografia2 = new File("temp/" + rs.getString("cedula") + ".jpg");
                                FileOutputStream canalSalida = new FileOutputStream(fotografia2);
                                canalSalida.write(byteHuella);
                                canalSalida.close();
                                //MOSTRAR LA IMAGEN EN LA VISTA PREVIA
                                ImageIcon imagenFoto = new ImageIcon("temp/"+rs.getString("cedula") + ".jpg");
                                Image imageAuxiliar = imagenFoto.getImage();
                                imageAuxiliar = imageAuxiliar.getScaledInstance(jLImagen.getWidth(), jLImagen.getHeight(), Image.SCALE_AREA_AVERAGING);
                                imagenFoto.setImage(imageAuxiliar);
                                jLImagen.setIcon(imagenFoto);
                                jLImagen.updateUI();
                            }
                            System.out.println("mi perfil es : "+padre.perfil);
                            validPerfil(padre.perfil);
                            
                        }else{
                            JOptionPane.showMessageDialog(null, "<html><B>CONTRASEÑA INCORRECTA..!</html>", "Error en Contraseña.", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "<html>Hay algún <b>campo vacio</b></html>\nPor favor Rectifique..!", "Error fjvh", JOptionPane.ERROR_MESSAGE);
                }
            }
        }catch(Exception er){
            JOptionPane.showMessageDialog(null, "error logueandome : "+er.toString());
        }
    }

    //metodo para habilitar batones segun el perfril
    public void validPerfil(String perfil){
        padre.bProductos.setEnabled(true);
        padre.bVentas.setEnabled(true);
        padre.bConsultas.setEnabled(true);
        padre.bLogueo.setEnabled(true);
        //ahora los radioButton
        padre.jMCrearProductos.setEnabled(true);
        padre.jMGenerarVenta.setEnabled(true);
        padre.jMReportar.setEnabled(true);
        padre.jMCambioSession.setEnabled(true);
        if(perfil.equalsIgnoreCase("Administrador")){
            padre.bUsuario.setEnabled(true);
            padre.bConfiguracion.setEnabled(true);
            //los radio
            padre.jMCrearUsuario.setEnabled(true);
            padre.jMPanelConf.setEnabled(true);
        }
    }

    private void jPPasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPPasswordFieldKeyPressed
        ingresarSistema(evt);
    }//GEN-LAST:event_jPPasswordFieldKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        try{
            //cargo la imagen de empresa
            ImageIcon imagenFoto = new ImageIcon("temp/refrigeracion.JPG");
            Image imageAuxiliar = imagenFoto.getImage();
            imageAuxiliar = imageAuxiliar.getScaledInstance(jLImagenEmpresa.getWidth(), jLImagenEmpresa.getHeight(), Image.SCALE_AREA_AVERAGING);
            imagenFoto.setImage(imageAuxiliar);
            jLImagenEmpresa.setIcon(imagenFoto);
            jLImagenEmpresa.updateUI();
            //jLImagenEmpresaCambio
//            /*ImageIcon */imagenFoto = new ImageIcon("temp/refrigeracion.JPG");
//            /*Image */imageAuxiliar = imagenFoto.getImage();
//            imageAuxiliar = imageAuxiliar.getScaledInstance(jLImagenEmpresaCambio.getWidth(), jLImagenEmpresaCambio.getHeight(), Image.SCALE_AREA_AVERAGING);
//            imagenFoto.setImage(imageAuxiliar);
//            jLImagenEmpresaCambio.setIcon(imagenFoto);
//            jLImagenEmpresaCambio.updateUI();
            //******
//            /*ImageIcon */imagenFoto = new ImageIcon("temp/refrigeracion.JPG");
//            /*Image */imageAuxiliar = imagenFoto.getImage();
//            imageAuxiliar = imageAuxiliar.getScaledInstance(jLImagen2.getWidth(), jLImagen2.getHeight(), Image.SCALE_AREA_AVERAGING);
//            imagenFoto.setImage(imageAuxiliar);
//            jLImagen2.setIcon(imagenFoto);
//            jLImagen2.updateUI();

        }catch(Exception er){
            System.out.println("error montando imagen de la empresa : "+er.toString());
        }
        
        //deshabilito los botones de facturacion y cotizacion
        jLNuevaContrasena.setVisible(false);
        jPContrasena1.setVisible(false);
        jLContrasenaOtraVez.setVisible(false);
        jPContrasenaNuevamente.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void jPContrasenaActualKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPContrasenaActualKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            //verifico q la contraseña coinsida con el Usuario actual del sistema
            try{
                if(padre.contrasena.equals(jPContrasenaActual.getText())){
                    //EN ESTE PUNTO LAS CONTRASENAS SON INGUALES
                    jLNuevaContrasena.setVisible(true);
                    jPContrasena1.setVisible(true);
                    jLContrasenaOtraVez.setVisible(true);
                    jPContrasenaNuevamente.setVisible(true);
                }
            }catch(Exception err){
                JOptionPane.showMessageDialog(null, "<html><b>Antes de Cambial la contraseña debes ingresar al sistema, con el usuario y contraseña actuales..!</b></html>", "error al intenta Cambial la contraseña", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jPContrasenaActualKeyPressed

    private void jLAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLAtrasMouseEntered
        jLAtras.setText("<html><u>"+jLAtras.getText()+"</u></html>");
    }//GEN-LAST:event_jLAtrasMouseEntered

    private void jLAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLAtrasMouseExited
        jLAtras.setText("...Atras");
    }//GEN-LAST:event_jLAtrasMouseExited

    private void jLAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLAtrasMouseClicked
        jPGlobal.removeAll();
        jPGlobal.add(jPLoguearUsuario);
        jTCampoUsuario.grabFocus();
        jPGlobal.updateUI();
    }//GEN-LAST:event_jLAtrasMouseClicked

    //valido que los cam,pos no es te vacios y q su contenido sea identico
    public boolean valCampos(){
        if(!jPContrasena1.getText().isEmpty() && !jPContrasenaNuevamente.getText().isEmpty() && (jPContrasena1.getText().equals(jPContrasenaNuevamente.getText()))){
            return true;
        }else{
            return false;
        }
    }

    private void jBCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCargarActionPerformed
        if(valCampos()){
            //ACTUALIZO PARA GUARDAR LA NUEVA CNTRASEÑA
            try{
                padre.conectorMySql.sentencia.executeUpdate("UPDATE usuario SET password = '"+jPContrasenaNuevamente.getText()+"' WHERE nombres = '"+padre.usuario+"' ");
                JOptionPane.showMessageDialog(null, "<html>Los datos de usuario <b>"+padre.usuario+"</b> se han actualizado de manera Satisfactoria..!</html>\n<html>Si presenta algun inconveniente y/o duda, comuniquese con el <b>Desarrollador de la Aplicacion.</b></html>", "Actualizacion correcta", JOptionPane.INFORMATION_MESSAGE);
                this.jPContrasenaActual.setText("");
                this.jPContrasena1.setText("");
                this.jPContrasenaNuevamente.setText("");
            }catch(Exception er){
                JOptionPane.showMessageDialog(null, "error actrualizando contrasena : "+er.toString());
            }
        }else{
            JOptionPane.showMessageDialog(null, "FALTA INFORMACOIN O NO COINCIDEN LAS CAMPOS DE LA NUEVA CONTRASEÑA  ..!", "Informacion faltante", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBCargarActionPerformed

    private void jLCambiarContrasenaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCambiarContrasenaMouseEntered
        jLCambiarContrasena.setText("<html><b><u>Cambiar mi Contraseña </u></b></html>");
    }//GEN-LAST:event_jLCambiarContrasenaMouseEntered

    private void jLCambiarContrasenaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCambiarContrasenaMouseExited
        jLCambiarContrasena.setText("Cambiar mi Contraseña");
    }//GEN-LAST:event_jLCambiarContrasenaMouseExited

    private void jLCambiarContrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCambiarContrasenaMouseClicked
        jPGlobal.removeAll();
        jPGlobal.add(jPCambiarContrasena);
        jPContrasenaActual.grabFocus();
        jPGlobal.updateUI();
//        Dimension dim = new Dimension(34, 14);
//        jLImagenEmpresaCambio.setPreferredSize(dim);
//        if(jLImagenEmpresaCambio.getWidth()>0){
//            jPGlobal.updateUI();
//            jPGlobal.updateUI();
//            System.out.println("se hizo visible..");
//            System.out.println("se hizo visible..");
//            ImageIcon imagenFoto = new ImageIcon("temp/refrigeracion.JPG");
//            Image imageAuxiliar = imagenFoto.getImage();
//            imageAuxiliar = imageAuxiliar.getScaledInstance(jLImagenEmpresaCambio.getWidth(), jLImagenEmpresaCambio.getHeight(), Image.SCALE_AREA_AVERAGING);
//            imagenFoto.setImage(imageAuxiliar);
//            jLImagenEmpresaCambio.setIcon(imagenFoto);
//            jLImagenEmpresaCambio.updateUI();
//        }
    }//GEN-LAST:event_jLCambiarContrasenaMouseClicked

    private void jLOlvideContrasenaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLOlvideContrasenaMouseEntered
        jLOlvideContrasena.setText("<html><b><u>Olvide mi Contraseña </u></b></html>");
    }//GEN-LAST:event_jLOlvideContrasenaMouseEntered

    private void jLOlvideContrasenaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLOlvideContrasenaMouseExited
        jLOlvideContrasena.setText("Olvide mi Contraseña");
    }//GEN-LAST:event_jLOlvideContrasenaMouseExited

    private void jLOlvideContrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLOlvideContrasenaMouseClicked
        jPGlobal.removeAll();
        jPGlobal.add(jPRecuperarContrasena);
        jTDireccionEmail.grabFocus();
        jPGlobal.updateUI();
//        if(jPRecuperarContrasena.isVisible()){
//            jPGlobal.updateUI();
//            jPGlobal.updateUI();
//            System.out.println("se hizo visible..");
//            System.out.println("se hizo visible..");
//            ImageIcon imagenFoto = new ImageIcon("temp/refrigeracion.JPG");
//            Image imageAuxiliar = imagenFoto.getImage();
//            imageAuxiliar = imageAuxiliar.getScaledInstance(jLImagen2.getWidth(), jLImagen2.getHeight(), Image.SCALE_AREA_AVERAGING);
//            imagenFoto.setImage(imageAuxiliar);
//            jLImagen2.setIcon(imagenFoto);
//            jLImagen2.updateUI();
//        }
    }//GEN-LAST:event_jLOlvideContrasenaMouseClicked

    //recuperar contraseña
    public void recupContrasena(){
         try{
             int adicional = aleatorio.nextInt(1724);
             boolean realizado = false;
             String contrasenaNueva = null;
             if(!jTDireccionEmail.getText().isEmpty()){
                ResultSet rs = padre.conectorMySql.sentencia.executeQuery("SELECT * FROM usuario WHERE e_mail = '"+jTDireccionEmail.getText().toLowerCase()+"'");
                if(rs.next()){
                    realizado = true;
                    contrasenaNueva = rs.getString("cedula")+adicional;
                    System.out.println("la contraseña nueva es : "+contrasenaNueva);
                    String mensaje = "<html>Saludos..!</html>";
                    mensaje+="<html><BR><BR>Usuario : <b>"+rs.getString("user")+"</b></html>";
                    mensaje+="<html><BR>Contraseña : <b>"+contrasenaNueva+"</b></html>";
                    mensaje+="<html><BR><BR>Esta Contraseña es generada de forma aleatoria, con ella podra ingresar al Sistema y posteriormente Cambiarla y dejarla a su gusto.</html>";
                    mensaje+="<html><P><P><P><font color="+"Silver"+">FIDEL JOSE VILLERO DE HOYOS.<BR>Analista y Desarrollador De Sistemas.</font><html>";
                    //JOptionPane.showMessageDialog(null, mensaje);
                    enviarCorreo(jTDireccionEmail.getText().toLowerCase(), "Olvide mi Contraseña (Help ne..!)", mensaje);
                    //JOptionPane.showMessageDialog(null, "<html>Se le ha enviado un E_mail a la direccion que usted suministro<html>\nDespues de recibir el E_mail ingrese al sistema y Cambie su contraseña\n<html>Si presenta algun inconveniente y/o dudas, comuniquese con el <B>Desarrollador De La Aplicacion.</B></html>");
                }else{
                    JOptionPane.showMessageDialog(null,"<html>La direccion de E_mail <b>"+jTDireccionEmail.getText()+"</b> no se encuentra en nuestra Base De Datos</html>\nPOR FAVOR RECTIFIQUE HE INTENTE DE NUEVO..!", "E_mail invalido.", JOptionPane.ERROR_MESSAGE);
                }
                if(realizado){
                    //cambio la clave actual para que pueda ingresar con la nueva clave
                    padre.conectorMySql.sentencia.executeUpdate("UPDATE usuario SET password = '"+contrasenaNueva+"' WHERE user = '"+padre.usuario+"'");
                    JOptionPane.showMessageDialog(null, "<html>Se le ha enviado un E_mail a la direccion que usted suministro<html>\nDespues de recibir el E_mail ingrese al sistema y Cambie su contraseña\n<html>Si presenta algun inconveniente y/o dudas, comuniquese con el <B>Desarrollador De La Aplicacion.</B></html>");
                }
             }
        }catch(Exception er){
            System.out.println("ERROR CON EL CORREO : "+er.toString());
        }
    }

    private void jBEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEnviarActionPerformed
       recupContrasena();
    }//GEN-LAST:event_jBEnviarActionPerformed

    private void jLAtras2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLAtras2MouseEntered
        jLAtras2.setText("<html><b><u>... Atras</u></b></html>");
    }//GEN-LAST:event_jLAtras2MouseEntered

    private void jLAtras2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLAtras2MouseExited
        jLAtras2.setText("... Atras");
    }//GEN-LAST:event_jLAtras2MouseExited

    private void jLAtras2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLAtras2MouseClicked
        jPGlobal.removeAll();
        jPGlobal.add(jPLoguearUsuario);
        jTCampoUsuario.grabFocus();
        jPGlobal.updateUI();
    }//GEN-LAST:event_jLAtras2MouseClicked

    /* este  metodo lo utilizo para enviar correos y le mando por parametros los datos requeridos
     como el padre que es la clase de la cual depende, el destino (Dir final), asunto y por ultimo
     el mensaje */
    public void enviarCorreo(String destinatario,String asunto, String mensaje){
        try{
            // Propiedades de la conexión
            Properties props = new Properties();
            //Configuramos el Proxy de Nuestra Red

            //ESTABLECEMOS EL PROXY, ES DECIR, INDICAMOS SI ESTAMOS UTILIZANDO PROXY
            props.setProperty("http.proxySet", "true");
            props.setProperty("http.proxyHost", "proxy2.sena.edu.co");
            props.setProperty("http.proxyPort", "80");

            props.setProperty("mail.smtp.starttls.enable", "true");
            //SERVIDOR SMTP DEL CUAL ENVIAREMOS EL CORREO
            props.setProperty("mail.smtp.host", "smtp.gmail.com");
            props.setProperty("mail.smtp.starttls.enable", "true");
            props.setProperty("mail.smtp.port", "587");
            props.setProperty("mail.smtp.user", "softfbcontrol@gmail.com");
            props.setProperty("mail.smtp.auth", "true");

            // Preparamos la sesion
            Session session = Session.getDefaultInstance(props);

            //CONSTRUIMOS EL MENSAJE
            MimeMessage message = new MimeMessage(session);
            message.setFrom(new InternetAddress("softfbcontrol@gmail.com"));
            message.setDescription("WEBMASTER EJEMPLO");
            //Agregamos los detinatarios del Correo.
            String destinatarios[] = destinatario.split(";");
            for(int i=0;i<destinatarios.length;i++){
                message.addRecipient(Message.RecipientType.TO,new InternetAddress(destinatarios[i].trim()));
            }
            message.setSubject(asunto);
            message.setText(mensaje, "ISO-8859-1","html");

            // En este punto enviamos el correo
            Transport t = session.getTransport("smtp");
            //Cuenta SMTP de Gmail para la validación (Dir y Password).
            t.connect("softfbcontrol@gmail.com", "ipstolusalud");
            t.sendMessage(message, message.getAllRecipients());
            t.close();
        }catch (Exception e){
            e.printStackTrace();
        }
    }//Fin del Envio de Correos

    /**
    * @param args the command line arguments
    */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCargar;
    private javax.swing.JButton jBEnviar;
    private javax.swing.JLabel jLAtras;
    private javax.swing.JLabel jLAtras2;
    private javax.swing.JLabel jLCambiarContrasena;
    private javax.swing.JLabel jLContrasenaOtraVez;
    private javax.swing.JLabel jLImagen;
    private javax.swing.JLabel jLImagen2;
    private javax.swing.JLabel jLImagenEmpresa;
    private javax.swing.JLabel jLImagenEmpresaCambio;
    private javax.swing.JLabel jLImagenUser;
    private javax.swing.JLabel jLMensajeBienvenida;
    private javax.swing.JLabel jLNuevaContrasena;
    private javax.swing.JLabel jLOlvideContrasena;
    private javax.swing.JLabel jLTextoBienvenida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPCambiarContrasena;
    private javax.swing.JPasswordField jPContrasena1;
    private javax.swing.JPasswordField jPContrasenaActual;
    private javax.swing.JPasswordField jPContrasenaNuevamente;
    private javax.swing.JPanel jPGlobal;
    private javax.swing.JPanel jPImagen;
    private javax.swing.JPanel jPImagenUser;
    private javax.swing.JPanel jPLoguearUsuario;
    private javax.swing.JPasswordField jPPasswordField;
    private javax.swing.JPanel jPRecuperarContrasena;
    private javax.swing.JTextField jTCampoUsuario;
    private javax.swing.JTextField jTDireccionEmail;
    // End of variables declaration//GEN-END:variables

}
