
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.sql.Blob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelConfiguracion.java
 *
 * Created on 04-may-2011, 10:24:35
 */

/**
 *
 * @author Administrador
 */
public class PanelConfiguracion extends javax.swing.JDialog {

    JFileChooser explorador = new JFileChooser();
    File fotografia;
    VentanaPrincipal padre;
    public DemoCalendario dCale = new DemoCalendario("Fecha De Ingreso De Gastos");
    public DemoCalendario dCale2 = new DemoCalendario("Fecha De Ingreso De Gastos");
    String fecha = null;
    String consecutivo = null;

    public PanelConfiguracion(VentanaPrincipal padre, boolean modal) {
        super(padre, modal);
        this.padre = padre;
        initComponents();
        dCale.setTfecha(jTAnio,0);
        dCale2.setTfecha(jTAnio,0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPMenuEmergente = new javax.swing.JPopupMenu();
        jMCargarFoto = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPGlobal = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPIzquierda = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLListaProductos = new javax.swing.JList();
        jPDerecha = new javax.swing.JPanel();
        jLImagenEmpresa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTStock = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTPrecioEntrada = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTPrecioVenta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTCantidad = new javax.swing.JTextField();
        jPImagen = new javax.swing.JPanel();
        jLImagen = new javax.swing.JLabel();
        jBActualizar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTProveedor = new javax.swing.JTextField();
        jPGlobalGastos = new javax.swing.JPanel();
        jTPanelPestanas = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        botonCalendarioFechaExpedicion = new javax.swing.JButton();
        jLImageEmpresa = new javax.swing.JLabel();
        jLUsuario = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTMonto = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTMotivo = new javax.swing.JTextArea();
        jBGuardar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTAnio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPModificarGastos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPCotenedorFechas = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLFechas = new javax.swing.JList();
        jLabel9 = new javax.swing.JLabel();
        jTMontoModificar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTFechaModGasto = new javax.swing.JTextField();
        botonCalendarioFechaExpedicion1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTAMotivo = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jBActualizarGastos = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPShowGastos = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jCMes = new javax.swing.JComboBox();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTablaGastos = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTAMotivoVer = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jCAnio = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jTBarraEstado = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPVerFacturas = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jCAnio1 = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jCMes1 = new javax.swing.JComboBox();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTablaFactura = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jLCantidadDeFilas = new javax.swing.JLabel();
        jLMontoFacturas = new javax.swing.JLabel();
        jTBarraEstadoFactura = new javax.swing.JTextField();

        jMCargarFoto.setText("Cargar Imagen del producto");
        jMCargarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCargarFotoActionPerformed(evt);
            }
        });
        jPMenuEmergente.add(jMCargarFoto);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PANEL DE CONFIGURACION");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPGlobal.setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(170);

        jPIzquierda.setLayout(new java.awt.BorderLayout());

        jLListaProductos.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLListaProductos.setForeground(new java.awt.Color(51, 102, 255));
        jLListaProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jLListaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLListaProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jLListaProductos);

        jPIzquierda.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(jPIzquierda);

        jPDerecha.setBackground(new java.awt.Color(255, 255, 255));

        jLImagenEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLabel2.setText("*  Nombre Del Producto :");

        jTNombre.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLabel3.setText("* Codigo :");

        jTCodigo.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLabel4.setText("* Stock :");

        jTStock.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTStock.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLabel5.setText("* Precio De Entrada :");

        jTPrecioEntrada.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTPrecioEntrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLabel6.setText("* Precio De Venta :");

        jTPrecioVenta.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTPrecioVenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLabel7.setText("* Cantidad En Bodega :");

        jTCantidad.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jPImagen.setBackground(new java.awt.Color(255, 255, 255));
        jPImagen.setLayout(new java.awt.BorderLayout());

        jLImagen.setBackground(new java.awt.Color(255, 255, 255));
        jLImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLImagen.setText("Imagen");
        jLImagen.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLImagen.setComponentPopupMenu(jPMenuEmergente);
        jPImagen.add(jLImagen, java.awt.BorderLayout.CENTER);

        jBActualizar.setText("Actualizar");
        jBActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLabel8.setText("* Porveedor :");

        jTProveedor.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTProveedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPDerechaLayout = new javax.swing.GroupLayout(jPDerecha);
        jPDerecha.setLayout(jPDerechaLayout);
        jPDerechaLayout.setHorizontalGroup(
            jPDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDerechaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLImagenEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(jPDerechaLayout.createSequentialGroup()
                        .addGroup(jPDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(jPDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTStock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDerechaLayout.createSequentialGroup()
                        .addGroup(jPDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTPrecioEntrada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTCantidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPDerechaLayout.createSequentialGroup()
                                .addComponent(jBActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTProveedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jPDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTPrecioVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPDerechaLayout.setVerticalGroup(
            jPDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDerechaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLImagenEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDerechaLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPDerechaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDerechaLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTPrecioEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPDerechaLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDerechaLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(jPDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBActualizar)
                            .addComponent(jButton2)))
                    .addComponent(jPImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPDerecha);

        jPGlobal.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Conf. Productos", jPGlobal);

        jPGlobalGastos.setBackground(new java.awt.Color(255, 255, 255));
        jPGlobalGastos.setLayout(new java.awt.BorderLayout());

        jTPanelPestanas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTPanelPestanasMouseClicked(evt);
            }
        });

        jPanel1.add(dCale);
        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        botonCalendarioFechaExpedicion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calendario.gif"))); // NOI18N
        botonCalendarioFechaExpedicion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonCalendarioFechaExpedicion.setMaximumSize(new java.awt.Dimension(16, 16));
        botonCalendarioFechaExpedicion.setMinimumSize(new java.awt.Dimension(16, 16));
        botonCalendarioFechaExpedicion.setPreferredSize(new java.awt.Dimension(16, 16));
        botonCalendarioFechaExpedicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalendarioFechaExpedicionActionPerformed(evt);
            }
        });

        jLImageEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLImageEmpresa.setText("<html>Esta Pestaña le permite <b>Ingresar Gastos</b>. Lo cual es una Informacion Relevante en el momento de Tomar desiciones. Recuerde que cuenta con <b>150 Caracteres </b> para la Descripcion del Mismo.</html>");

        jLUsuario.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLUsuario.setForeground(new java.awt.Color(102, 102, 255));
        jLUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLUsuario.setText("jLabel9");

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLabel10.setText("* Monto en Pesos :");

        jTMonto.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTMonto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTMontoKeyTyped(evt);
            }
        });

        jTMotivo.setColumns(20);
        jTMotivo.setRows(5);
        jScrollPane2.setViewportView(jTMotivo);

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLabel11.setText("* Fecha :");

        jTAnio.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTAnio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTAnio.setFocusable(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLabel12.setText("* Motivo del Gasto  :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jBGuardar)
                        .addGap(50, 50, 50)
                        .addComponent(jBCancelar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLImageEmpresa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jTMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTAnio, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botonCalendarioFechaExpedicion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(220, 220, 220)))
                    .addComponent(jLabel12))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLImageEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLUsuario)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botonCalendarioFechaExpedicion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTAnio, javax.swing.GroupLayout.Alignment.LEADING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGuardar)
                    .addComponent(jBCancelar))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jTPanelPestanas.addTab("Ingresar Gastos", jPanel1);

        jPModificarGastos.add(dCale2);
        jPModificarGastos.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html>En esta Pestaña puedes modificar los gastos, ya sea que anteriormente hallas digitado mal, y/o erraras en tus cuentas, (Recuerda que los <b>Datos</b> que ingreses al Sistema deben ser fieles a la relidad, para que los reportes y procesos realizados brinden Datos exactos que te ayuden a una posterior toma de Desiciones.)</html>");

        jPCotenedorFechas.setBackground(new java.awt.Color(255, 255, 255));
        jPCotenedorFechas.setBorder(javax.swing.BorderFactory.createTitledBorder("Escoger Fecha "));
        jPCotenedorFechas.setLayout(new java.awt.BorderLayout());

        jLFechas.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLFechas.setForeground(new java.awt.Color(102, 102, 255));
        jLFechas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLFechasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jLFechas);

        jPCotenedorFechas.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLabel9.setText("* Monto en Pesos :");

        jTMontoModificar.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTMontoModificar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLabel13.setText("* Fecha :");

        jTFechaModGasto.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTFechaModGasto.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        botonCalendarioFechaExpedicion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calendario.gif"))); // NOI18N
        botonCalendarioFechaExpedicion1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonCalendarioFechaExpedicion1.setMaximumSize(new java.awt.Dimension(16, 16));
        botonCalendarioFechaExpedicion1.setMinimumSize(new java.awt.Dimension(16, 16));
        botonCalendarioFechaExpedicion1.setPreferredSize(new java.awt.Dimension(16, 16));
        botonCalendarioFechaExpedicion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalendarioFechaExpedicion1ActionPerformed(evt);
            }
        });

        jTAMotivo.setColumns(20);
        jTAMotivo.setRows(5);
        jScrollPane4.setViewportView(jTAMotivo);

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLabel14.setText("* Motivo del Gasto :");

        jBActualizarGastos.setText("Actualizar");
        jBActualizarGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarGastosActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPModificarGastosLayout = new javax.swing.GroupLayout(jPModificarGastos);
        jPModificarGastos.setLayout(jPModificarGastosLayout);
        jPModificarGastosLayout.setHorizontalGroup(
            jPModificarGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPModificarGastosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPModificarGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPModificarGastosLayout.createSequentialGroup()
                        .addComponent(jPCotenedorFechas, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPModificarGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPModificarGastosLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPModificarGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPModificarGastosLayout.createSequentialGroup()
                                        .addGroup(jPModificarGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTMontoModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(49, 49, 49)
                                        .addGroup(jPModificarGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                            .addGroup(jPModificarGastosLayout.createSequentialGroup()
                                                .addComponent(jTFechaModGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(botonCalendarioFechaExpedicion1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPModificarGastosLayout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jBActualizarGastos)
                                .addGap(31, 31, 31)
                                .addComponent(jButton3))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPModificarGastosLayout.setVerticalGroup(
            jPModificarGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPModificarGastosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPModificarGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPModificarGastosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPModificarGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13))
                        .addGroup(jPModificarGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPModificarGastosLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPModificarGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTMontoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFechaModGasto)))
                            .addGroup(jPModificarGastosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCalendarioFechaExpedicion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPModificarGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBActualizarGastos)
                            .addComponent(jButton3))
                        .addGap(34, 34, 34))
                    .addGroup(jPModificarGastosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPCotenedorFechas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(79, 79, 79))
        );

        jTPanelPestanas.addTab("Modificar Gastos", jPModificarGastos);

        jPShowGastos.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("<html>Esta pestaña te permite ver los <B>Gastos</B> en un mes Determinado. Y haciendo Click en cualquiera las filas puedes ver el Texto Completo en el que se Describe el Motivo del gasto. </html>");

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLabel16.setText("* Seleccionar el mes :");

        jCMes.setFont(new java.awt.Font("Tahoma", 1, 11));
        jCMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jTablaGastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Reporta", "Asunto", "Monto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablaGastos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablaGastosMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTablaGastos);

        jTAMotivoVer.setColumns(20);
        jTAMotivoVer.setRows(5);
        jScrollPane6.setViewportView(jTAMotivoVer);

        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLabel17.setText("* Motivo :");

        jLabel18.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLabel18.setText("* Seleccionar el Año :");

        jCAnio.setFont(new java.awt.Font("Tahoma", 1, 11));
        jCAnio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        jCAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCAnioActionPerformed(evt);
            }
        });

        jButton1.setText("Mostrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPShowGastosLayout = new javax.swing.GroupLayout(jPShowGastos);
        jPShowGastos.setLayout(jPShowGastosLayout);
        jPShowGastosLayout.setHorizontalGroup(
            jPShowGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPShowGastosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPShowGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPShowGastosLayout.createSequentialGroup()
                        .addComponent(jCMes, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addGroup(jPShowGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPShowGastosLayout.createSequentialGroup()
                                .addComponent(jCAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(jButton1)))
                        .addContainerGap(111, Short.MAX_VALUE))
                    .addGroup(jPShowGastosLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(418, Short.MAX_VALUE))
                    .addGroup(jPShowGastosLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addContainerGap(506, Short.MAX_VALUE))
                    .addGroup(jPShowGastosLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPShowGastosLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPShowGastosLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        jPShowGastosLayout.setVerticalGroup(
            jPShowGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPShowGastosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPShowGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18))
                .addGap(9, 9, 9)
                .addGroup(jPShowGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jTPanelPestanas.addTab("Ver Gastos", jPShowGastos);

        jPGlobalGastos.add(jTPanelPestanas, java.awt.BorderLayout.CENTER);
        jPGlobalGastos.add(jTBarraEstado, java.awt.BorderLayout.SOUTH);

        jTabbedPane1.addTab("Gastos Efectuados", jPGlobalGastos);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPVerFacturas.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("text");

        jLabel20.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel20.setText("Seleccionar Año :");

        jCAnio1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jCAnio1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        jCAnio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCAnio1ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel21.setText("Seleccionar Mes :");

        jCMes1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCMes1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jCMes1.setEnabled(false);
        jCMes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCMes1ActionPerformed(evt);
            }
        });

        jTablaFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Vendedor", "Cantidad", "Productos", "Precio_Unidad", "Sub_Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablaFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablaFacturaMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jTablaFactura);

        jLabel22.setText("Ventas Efectuadas en el Mes :");

        jLCantidadDeFilas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLCantidadDeFilas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLMontoFacturas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLMontoFacturas.setForeground(new java.awt.Color(102, 102, 255));
        jLMontoFacturas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLMontoFacturas.setText("jLabel23");

        javax.swing.GroupLayout jPVerFacturasLayout = new javax.swing.GroupLayout(jPVerFacturas);
        jPVerFacturas.setLayout(jPVerFacturasLayout);
        jPVerFacturasLayout.setHorizontalGroup(
            jPVerFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVerFacturasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPVerFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPVerFacturasLayout.createSequentialGroup()
                        .addGroup(jPVerFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPVerFacturasLayout.createSequentialGroup()
                                .addGroup(jPVerFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jCAnio1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(67, 67, 67)
                                .addGroup(jPVerFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCMes1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21))))
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(jPVerFacturasLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLCantidadDeFilas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                        .addComponent(jLMontoFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))))
            .addGroup(jPVerFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPVerFacturasLayout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                    .addGap(14, 14, 14)))
        );
        jPVerFacturasLayout.setVerticalGroup(
            jPVerFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVerFacturasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPVerFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPVerFacturasLayout.createSequentialGroup()
                        .addGroup(jPVerFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPVerFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCAnio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCMes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                        .addGroup(jPVerFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLCantidadDeFilas, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLMontoFacturas))
                .addContainerGap())
            .addGroup(jPVerFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPVerFacturasLayout.createSequentialGroup()
                    .addGap(138, 138, 138)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(57, Short.MAX_VALUE)))
        );

        jPanel2.add(jPVerFacturas, java.awt.BorderLayout.CENTER);
        jPanel2.add(jTBarraEstadoFactura, java.awt.BorderLayout.SOUTH);

        jTabbedPane1.addTab("Ver Facturas", jPanel2);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMCargarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCargarFotoActionPerformed
        try{
            explorador.setMultiSelectionEnabled(false);
            explorador.setDialogTitle("Seleccione una Imagen..!");
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Imagenes (*.png, *.jpg, *.gif)", "png","jpg", "gif");
            explorador.setFileFilter(filter);
            if(explorador.showOpenDialog(PanelConfiguracion.this)== JFileChooser.APPROVE_OPTION){
                fotografia = explorador.getSelectedFile();
                ImageIcon imagen = new ImageIcon(explorador.getSelectedFile().getCanonicalPath());
                java.awt.Image escala = imagen.getImage();
                escala = escala.getScaledInstance(jLImagen.getWidth(),jLImagen.getHeight(), java.awt.Image.SCALE_AREA_AVERAGING);
                imagen.setImage(escala);
                jLImagen.setIcon(imagen);
                jLImagen.updateUI();
            }
        }catch(Exception error){
            System.out.println("Error accediendo al archivo : "+error.toString());
        }
    }//GEN-LAST:event_jMCargarFotoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try{
            //coloco la imagen
            jLMontoFacturas.setVisible(false);
            ImageIcon imagenFoto = new ImageIcon("temp/refrigeracion.JPG");
            Image imageAuxiliar = imagenFoto.getImage();
            imageAuxiliar = imageAuxiliar.getScaledInstance(jLImagenEmpresa.getWidth(), jLImagenEmpresa.getHeight(), Image.SCALE_AREA_AVERAGING);
            imagenFoto.setImage(imageAuxiliar);
            jLImagenEmpresa.setIcon(imagenFoto);
            jLImagenEmpresa.updateUI();
            //cargo el usuario en gastos
            jLUsuario.setText(padre.usuario.toUpperCase());

            String sql = "SELECT * FROM productos";
            ResultSet rs = padre.conectorMySql.sentencia.executeQuery(sql);
            while(rs.next()){
                rs.last();
                String strings[] = new String[rs.getRow()];
                rs.beforeFirst();
                int auxiliar = 0;
                int auxiliar1 = 0;
                while(rs.next()){
                    strings[auxiliar] = rs.getString("nombre").toUpperCase();//"+"_"+resultadoQuery.getString("apellidos").toUpperCase();
                    auxiliar++;
                }
                final String stringReal[] = strings;
                jLListaProductos.setModel(new javax.swing.AbstractListModel() {
                    public int getSize() { return stringReal.length; }
                    public Object getElementAt(int i) { return stringReal[i]; }
                });
                jLListaProductos.updateUI();
           }
        }catch(Exception er){
            JOptionPane.showMessageDialog(null, "error ingresando en la lista : "+er.toString());
        }
    }//GEN-LAST:event_formWindowOpened

    private void jLListaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLListaProductosMouseClicked
        //consulto el producto y muestro sus propiedades
        try{
            jLImagen.setText(null);
            String sql = "SELECT * FROM productos WHERE nombre = '"+jLListaProductos.getSelectedValue().toString()+"' ";
            ResultSet rs = padre.conectorMySql.sentencia.executeQuery(sql);
            if(rs.next()){
                jTNombre.setText(rs.getString("nombre").toUpperCase());
                jTCodigo.setText(rs.getString("id"));
                jTStock.setText(rs.getString("stock"));
                jTPrecioEntrada.setText(rs.getString("precio_entrada"));
                jTPrecioVenta.setText(rs.getString("precio_venta_unidad"));
                jTCantidad.setText(rs.getString("cantidad"));
                jTProveedor.setText("proveedor");
                //cargo la imagen
                Blob foto = rs.getBlob("imagen");
                if(foto!=null){
                    byte[] byteHuella = foto.getBytes(1,(int)foto.length());
                    fotografia = new File("temp/" + rs.getString("id") + ".jpg");
                    FileOutputStream canalSalida = new FileOutputStream(fotografia);
                    canalSalida.write(byteHuella);
                    canalSalida.close();
                    //MOSTRAR LA IMAGEN EN LA VISTA PREVIA
                    ImageIcon imagenFoto = new ImageIcon("temp/"+rs.getString("id") + ".jpg");
                    Image imageAuxiliar = imagenFoto.getImage();
                    imageAuxiliar = imageAuxiliar.getScaledInstance(jLImagen.getWidth(), jLImagen.getHeight(), Image.SCALE_AREA_AVERAGING);
                    imagenFoto.setImage(imageAuxiliar);
                    jLImagen.setIcon(imagenFoto);
                    jLImagen.updateUI();
                }
            }
        }catch(Exception er){
            JOptionPane.showMessageDialog(null, "error cargando propiedades : "+er.toString());
        }
    }//GEN-LAST:event_jLListaProductosMouseClicked

    //valifar campos
    public boolean validaCampos(){
        if(jTNombre.getText().isEmpty() || jTCodigo.getText().isEmpty() || jTPrecioEntrada.getText().isEmpty() || jTCantidad.getText().isEmpty() || jTProveedor.getText().isEmpty() || jTStock.getText().isEmpty() || jTPrecioVenta.getText().isEmpty()){
            return false;
        }else{
            return true;
        }
    }

    //metodo en el q elimino y luego guardo la nueva informacion
    public void SaveInf(){
        if(validaCampos()){
            try{
                String fechaEntrada = null;
                String resividoPor = null;
                //String proveedor = null;
                //saco la fecha de entrada
                String sq = "SELECT fecha_entrada, resivido_por, proveedor FROM productos WHERE id = '"+jTCodigo.getText()+"'";
                ResultSet r = padre.conectorMySql.sentencia.executeQuery(sq);
                if(r.next()){
                    fechaEntrada = r.getString("fecha_entrada");
                    resividoPor = r.getString("resivido_por");
                    //proveedor = r.getString("proveedor");
                }
                //***
                String sql = "DELETE FROM productos WHERE id = '"+jTCodigo.getText()+"'";
                padre.conectorMySql.sentencia.execute(sql);
                System.out.println("en este punto ya se borro la inf.");
                //ahora guardo
                String sql2 = "INSERT INTO productos VALUES ('"+jTCodigo.getText()+"', '"+jTNombre.getText().toLowerCase()+"', "+jTStock.getText()+", '"+fechaEntrada+"', '"+jTPrecioEntrada.getText()+"', '"+jTPrecioVenta.getText()+"', "+jTCantidad.getText()+", '"+resividoPor+"', '"+jTProveedor.getText().toLowerCase()+"', null)";
                padre.conectorMySql.sentencia.execute(sql2);
                //almecano la imagen
                FileInputStream streamEntrada = new FileInputStream(fotografia);
                PreparedStatement pstmt = padre.conectorMySql.conexion.prepareStatement("UPDATE ferreteria.productos set imagen = ? WHERE id='"+jTCodigo.getText()+"'");
                pstmt.setBinaryStream(1, streamEntrada, (int)fotografia.length());
                pstmt.executeUpdate();
                pstmt.close();
                streamEntrada.close();
                JOptionPane.showMessageDialog(null, "<html>El producto <b>"+this.jTNombre.getText().toLowerCase()+"</b> con Codigo <b>"+this.jTCodigo.getText()+"</b> ha sido Actualizado Satisfactoriamente..! </html>");
            }catch(Exception er){
                JOptionPane.showMessageDialog(null, "error actualizando : "+er.toString());
            }
        }else{
            JOptionPane.showMessageDialog(null, "<html>Todos los campos marcados con <b>*</b> son de Caracter <b>Obligatorios.</b></html>\nPor favor Rectifique..!");
        }
    }

    private void jBActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarActionPerformed
        SaveInf();
    }//GEN-LAST:event_jBActualizarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void botonCalendarioFechaExpedicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalendarioFechaExpedicionActionPerformed
        dCale.saberFecha(jTAnio);
        dCale.titled.setTitle("Fecha del Gasto..!");
        dCale.posicionJIntenal((jTAnio.getLocation().x - 10),(jTAnio.getLocation().y + 17));
        dCale.setVisible(true);
}//GEN-LAST:event_botonCalendarioFechaExpedicionActionPerformed

    //validoque los campos no esten vacios
    public boolean validCampos(){
        if(!jTMonto.getText().isEmpty() && !jTAnio.getText().isEmpty() && !jTMotivo.getText().toLowerCase().isEmpty()){
            return true;
        }else{
            return false;
        }
    }

    public void limpiaCamposGastos(){
        jTMotivo.setText("");
        jTMonto.setText("");
        dCale.setTfecha(jTAnio,0);
    }

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        try{
            if(validCampos()){
                String sql = "INSERT INTO gastos VALUES ('"+padre.usuario.toLowerCase()+"', null, '"+jTAnio.getText()+"', '"+jTMonto.getText()+"', '"+jTMotivo.getText().toLowerCase()+"')";
                padre.conectorMySql.sentencia.execute(sql);
                JOptionPane.showMessageDialog(null, "<html>La informacion referente a los gastos en la fecha <b>"+jTAnio.getText()+"</b> se ha Guardado en la Base De Datos...</html>", "Gastos Guardados Satisfactoriamente", JOptionPane.INFORMATION_MESSAGE);
                limpiaCamposGastos();
            }else{
                JOptionPane.showMessageDialog(null, "<html>Uno de los Campos esta vacion. Recuerde que todos los Campos </html>\n<html>marcados con <b>(*)</b>son de Caracter <b>obligatorios</b></html>\nPor favor Rectifique..!", "Campo vacio", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception er){
            JOptionPane.showMessageDialog(null, "error guardando gastos : "+er.toString());
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jTMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTMontoKeyTyped
        //codigo para ingresar solo numeros en el texField
        if(evt.getKeyChar()!=KeyEvent.VK_ENTER){
            if(!Character.isDigit(evt.getKeyChar())){
                evt.consume();
            }
        }
    }//GEN-LAST:event_jTMontoKeyTyped

    private void botonCalendarioFechaExpedicion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalendarioFechaExpedicion1ActionPerformed
        dCale2.saberFecha(jTFechaModGasto);
        dCale2.titled.setTitle("Fecha del Gasto..!");
        dCale2.posicionJIntenal((jTFechaModGasto.getLocation().x - 10),(jTFechaModGasto.getLocation().y + 17));
        dCale2.setVisible(true);
    }//GEN-LAST:event_botonCalendarioFechaExpedicion1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTPanelPestanasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTPanelPestanasMouseClicked
        if(jPModificarGastos.isVisible()){
            System.out.println("voy a modificar gastos ");
            try{
                String sql = "SELECT * FROM gastos";
                ResultSet rs = padre.conectorMySql.sentencia.executeQuery(sql);
                while(rs.next()){
                    rs.last();
                    String strings[] = new String[rs.getRow()];
                    rs.beforeFirst();
                    int auxiliar = 0;
                    int auxiliar1 = 0;
                    while(rs.next()){
                        strings[auxiliar] = rs.getString("fecha")+" / "+rs.getString("consecutivo");
                        auxiliar++;
                    }
                    final String stringReal[] = strings;
                    jLFechas.setModel(new javax.swing.AbstractListModel() {
                        public int getSize() { return stringReal.length; }
                        public Object getElementAt(int i) { return stringReal[i]; }
                    });
                    jLFechas.updateUI();
               }
            }catch(Exception er){
                JOptionPane.showMessageDialog(null, "error mostrando fechas para adtualizar : "+er.toString());
            }

        }
        try{
            if(jPShowGastos.isVisible()){
                //cargo los años donde hay gastos
                Vector anios = new Vector();
                String fechas[] = null;
                String sqlGastos = "SELECT fecha FROM gastos ";
                   ResultSet rsg = padre.conectorMySql.sentencia.executeQuery(sqlGastos);
                    while(rsg.next()){
                        fechas = rsg.getString("fecha").split("-");
                        anios.add(fechas[0]);
//                        jCAnio.addItem(anio[0]);
//                        System.out.println("el anio es : "+anio[0]);
                    }
            }
        }catch(Exception er){
            JOptionPane.showMessageDialog(null, "error cargando anios : "+er.toString());
        }
        


        
    }//GEN-LAST:event_jTPanelPestanasMouseClicked

    //metodo para cargar datos
    public void cargarDatos(){
        try{
            //saco la fecha
            String[] datos = jLFechas.getSelectedValue().toString().split(" / ");
            fecha = datos[0];
            consecutivo = datos[1];
            System.out.println("la fecha es : "+fecha+" y el consecutivo es : "+consecutivo);
            ResultSet rs = padre.conectorMySql.sentencia.executeQuery("SELECT * FROM gastos WHERE consecutivo = "+consecutivo+" AND fecha = '"+fecha+"'");
            if(rs.next()){
                //coloco los datos en sus campos
                jTMontoModificar.setText(rs.getString("monto"));
                jTFechaModGasto.setText(rs.getString("fecha"));
                jTAMotivo.setText(rs.getString("motivo").toUpperCase());
            }
        }catch(Exception er){
            JOptionPane.showMessageDialog(null, "error cargando datos : "+er.toString());
        }
    }

    private void jLFechasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLFechasMouseClicked
        cargarDatos();
    }//GEN-LAST:event_jLFechasMouseClicked

    public void limpiarCamposActualizar(){
        jTMontoModificar.setText("");
        jTAMotivo.setText("");
    }

    //actualizar gastos
    public void updateGastos(){
        try{
            padre.conectorMySql.sentencia.executeUpdate("DELETE FROM gastos WHERE fecha = '"+fecha+"' AND consecutivo = '"+consecutivo+"'");
            //en este punto ya borre
            padre.conectorMySql.sentencia.execute("INSERT INTO gastos VALUES ('"+padre.usuario.toLowerCase()+"', "+consecutivo+", '"+fecha+"', '"+jTMontoModificar.getText()+"', '"+jTAMotivo.getText()+"')");
            JOptionPane.showMessageDialog(null, "El monto se ha Actualizado Satisfactotiamente..!");
            limpiarCamposActualizar();
        }catch(Exception er){
            JOptionPane.showMessageDialog(null, "error actualizando gastso : "+er.toString());
        }
    }

    private void jBActualizarGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarGastosActionPerformed
        updateGastos();
    }//GEN-LAST:event_jBActualizarGastosActionPerformed

    private void jTablaGastosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaGastosMouseClicked
        try{
            System.out.println("la fila seleccionada es : "+jTablaGastos.getSelectedRow());
            String sql = "SELECT * FROM gastos WHERE nombres = '"+jTablaGastos.getValueAt(jTablaGastos.getSelectedRow(), 1).toString()+"' AND fecha = '"+jTablaGastos.getValueAt(jTablaGastos.getSelectedRow(), 0).toString()+"' AND monto = '"+jTablaGastos.getValueAt(jTablaGastos.getSelectedRow(), 3).toString()+"' AND motivo = '"+jTablaGastos.getValueAt(jTablaGastos.getSelectedRow(), 2).toString()+"'";
            ResultSet rs2 = padre.conectorMySql.sentencia.executeQuery(sql);
            if(rs2.next()){
                jTAMotivoVer.setText(rs2.getString("motivo").toUpperCase());
            }
        }catch(Exception er){
            JOptionPane.showMessageDialog(null, "error cargando motivo de la tabla : "+er.toString());
        }
    }//GEN-LAST:event_jTablaGastosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            ((DefaultTableModel)jTablaGastos.getModel()).setRowCount(0);

            int fila = 0;
            int indiceMes = jCMes.getSelectedIndex() + 1;
            String numeroMes = ""+indiceMes;
            if(indiceMes<10){
                numeroMes = "0"+indiceMes;
            }
            //obtengo la fecha
            String fechaConsulta = jCAnio.getSelectedItem().toString()+"-"+numeroMes;
            System.out.println("el patron de busqueda es : "+fechaConsulta);
            String sql = "SELECT * FROM gastos WHERE fecha LIKE '"+fechaConsulta+"%'";
            ResultSet rs = padre.conectorMySql.sentencia.executeQuery(sql);
            while(rs.next()){
                ((DefaultTableModel)jTablaGastos.getModel()).setRowCount(jTablaGastos.getRowCount() + 1);
                jTablaGastos.setValueAt(rs.getString("fecha"), fila, 0);
                jTablaGastos.setValueAt(rs.getString("nombres"), fila, 1);
                jTablaGastos.setValueAt(rs.getString("motivo"), fila, 2);
                jTablaGastos.setValueAt(rs.getString("monto"), fila, 3);
                fila++;
            }
            if(fila == 0){
                JOptionPane.showMessageDialog(null, "<HTML>No se ha encontrado informacion en la fecha seleccionada..!</HTML>", "No hay informe", JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(Exception er){
            JOptionPane.showMessageDialog(null, "error cargando gastos por mes : "+er.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTablaFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaFacturaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTablaFacturaMouseClicked

    private void jCAnio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCAnio1ActionPerformed
        jCMes1.setEnabled(true);
    }//GEN-LAST:event_jCAnio1ActionPerformed

    //cargo las facturas
    public void CargarFacturas(){
        int total = 0;
        int auxFila = 0;
        int subTotal = 0;
        int cantidad = 0;
        int precioUnidad = 0;
        try{
            ((DefaultTableModel)jTablaFactura.getModel()).setRowCount(0);
            int numeroDelIndiceMes = jCMes1.getSelectedIndex() + 1;
            String Mess = ""+numeroDelIndiceMes;
            if(numeroDelIndiceMes<10){
                Mess = "0"+numeroDelIndiceMes;
            }
            String fechaFactura = jCAnio1.getSelectedItem().toString()+"-"+Mess;
            System.out.println("la fecha a consultar es : "+fechaFactura);
            String sql = "SELECT * FROM factura WHERE fecha LIKE '"+fechaFactura+"%'";
            ResultSet rs = padre.conectorMySql.sentencia.executeQuery(sql);
            while(rs.next()){
                ((DefaultTableModel)jTablaFactura.getModel()).setRowCount(jTablaFactura.getRowCount() + 1);
                cantidad = Integer.parseInt(rs.getString("cantidad"));
                precioUnidad = Integer.parseInt(rs.getString("precio_unidad"));
                subTotal = precioUnidad * cantidad;
                jTablaFactura.setValueAt(rs.getString("fecha"), auxFila, 0);
                jTablaFactura.setValueAt(rs.getString("vendedor"), auxFila, 1);
                jTablaFactura.setValueAt(cantidad, auxFila, 2);
                jTablaFactura.setValueAt(rs.getString("productos"), auxFila, 3);
                jTablaFactura.setValueAt(precioUnidad, auxFila, 4);
                jTablaFactura.setValueAt(subTotal, auxFila, 5);
                auxFila++;
                jLCantidadDeFilas.setText(""+auxFila);
            }
            //sumo las cantodades totales y las muestro en TOTAL
            for(int i=0;i<jTablaFactura.getRowCount(); i++){
                System.out.println("las cantidades a sumar son : "+cambiaInt(jTablaFactura.getValueAt(i, 5).toString()));
                total += cambiaInt(jTablaFactura.getValueAt(i, 5).toString()) ;
            }
            jLMontoFacturas.setText("$ "+total);
            jLMontoFacturas.setVisible(true);
        }catch(Exception er){
            JOptionPane.showMessageDialog(null, "error mostrando facturas : "+er.toString());
        }
    }

    //metodo para cambiar un texto a int
    public int cambiaInt(String num){
        return Integer.parseInt(num);
    }

    private void jCMes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCMes1ActionPerformed
        CargarFacturas();
        jTBarraEstadoFactura.setText("LISTADO DE VENTAS DEL MES DE "+jCMes1.getSelectedItem().toString()+" DE "+jCAnio1.getSelectedItem().toString()+"");
    }//GEN-LAST:event_jCMes1ActionPerformed

    private void jCAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCAnioActionPerformed

    }//GEN-LAST:event_jCAnioActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCalendarioFechaExpedicion;
    private javax.swing.JButton botonCalendarioFechaExpedicion1;
    private javax.swing.JButton jBActualizar;
    private javax.swing.JButton jBActualizarGastos;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jCAnio;
    private javax.swing.JComboBox jCAnio1;
    private javax.swing.JComboBox jCMes;
    private javax.swing.JComboBox jCMes1;
    private javax.swing.JLabel jLCantidadDeFilas;
    private javax.swing.JList jLFechas;
    private javax.swing.JLabel jLImageEmpresa;
    private javax.swing.JLabel jLImagen;
    private javax.swing.JLabel jLImagenEmpresa;
    private javax.swing.JList jLListaProductos;
    private javax.swing.JLabel jLMontoFacturas;
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMCargarFoto;
    private javax.swing.JPanel jPCotenedorFechas;
    private javax.swing.JPanel jPDerecha;
    private javax.swing.JPanel jPGlobal;
    private javax.swing.JPanel jPGlobalGastos;
    private javax.swing.JPanel jPImagen;
    private javax.swing.JPanel jPIzquierda;
    private javax.swing.JPopupMenu jPMenuEmergente;
    private javax.swing.JPanel jPModificarGastos;
    private javax.swing.JPanel jPShowGastos;
    private javax.swing.JPanel jPVerFacturas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTAMotivo;
    private javax.swing.JTextArea jTAMotivoVer;
    private javax.swing.JTextField jTAnio;
    private javax.swing.JTextField jTBarraEstado;
    private javax.swing.JTextField jTBarraEstadoFactura;
    private javax.swing.JTextField jTCantidad;
    private javax.swing.JTextField jTCodigo;
    private javax.swing.JTextField jTFechaModGasto;
    private javax.swing.JTextField jTMonto;
    private javax.swing.JTextField jTMontoModificar;
    private javax.swing.JTextArea jTMotivo;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTabbedPane jTPanelPestanas;
    private javax.swing.JTextField jTPrecioEntrada;
    private javax.swing.JTextField jTPrecioVenta;
    private javax.swing.JTextField jTProveedor;
    private javax.swing.JTextField jTStock;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTablaFactura;
    private javax.swing.JTable jTablaGastos;
    // End of variables declaration//GEN-END:variables

}
