
import java.awt.BorderLayout;
import java.awt.Color;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Reportes.java
 *
 * Created on 04-may-2011, 14:10:50
 */

/**
 *
 * @author Administrador
 */
public class Reportes extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;
    private DefaultPieDataset dataset;
    private DefaultCategoryDataset dataset2;
    private JFreeChart jfc;


    public Reportes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPReporte = new javax.swing.JPanel();
        jPEscojerAnio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REPORTE DE VENTAS");

        jPReporte.setBackground(new java.awt.Color(255, 255, 255));
        jPReporte.setBorder(javax.swing.BorderFactory.createTitledBorder("Reporte "));
        jPReporte.setMaximumSize(new java.awt.Dimension(583, 320));
        jPReporte.setPreferredSize(new java.awt.Dimension(583, 320));
        jPReporte.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPReporte, java.awt.BorderLayout.CENTER);

        jPEscojerAnio.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLabel1.setText("Escojer Años a Comparar :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLabel2.setText("y");

        jButton1.setText("Mostrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPEscojerAnioLayout = new javax.swing.GroupLayout(jPEscojerAnio);
        jPEscojerAnio.setLayout(jPEscojerAnioLayout);
        jPEscojerAnioLayout.setHorizontalGroup(
            jPEscojerAnioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEscojerAnioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPEscojerAnioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPEscojerAnioLayout.createSequentialGroup()
                        .addGroup(jPEscojerAnioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(jPEscojerAnioLayout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(349, Short.MAX_VALUE))
        );
        jPEscojerAnioLayout.setVerticalGroup(
            jPEscojerAnioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEscojerAnioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPEscojerAnioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPEscojerAnio, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void limpiarContenedorPrincipal(){
        jPReporte.removeAll();
        jPReporte.updateUI();
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        limpiarContenedorPrincipal();

        dataset2 = new DefaultCategoryDataset();
	dataset2.setValue(600000, "Mes2009", "Enero");
        dataset2.setValue(800000, "Mes2010", "Enero");

	dataset2.setValue(500000, "Mes2009", "Febrero");
        dataset2.setValue(900000, "Mes2010", "Febrero");

	dataset2.setValue(600000, "Mes2009", "Marzo");
        dataset2.setValue(400000, "Mes2010", "Marzo");

	dataset2.setValue(200000, "Mes2009", "Abril");
        dataset2.setValue(200000, "Mes2010", "Abril");

        dataset2.setValue(900000, "Mes2009", "Mayo");
        dataset2.setValue(600000, "Mes2010", "Mayo");

        dataset2.setValue(300000, "Mes2009", "Junio");
        dataset2.setValue(700000, "Mes2010", "Junio");

        dataset2.setValue(400000, "Mes2009", "Julio");
        dataset2.setValue(600000, "Mes2010", "Julio");

        dataset2.setValue(200000, "Mes2009", "Agosto");
        dataset2.setValue(200000, "Mes2010", "Agosto");

        jfc = ChartFactory.createBarChart3D("Comparacion de Ventas por Año","Meses del 2011", "Ventas $", dataset2, PlotOrientation.VERTICAL, true,true, false);
	CategoryPlot p = jfc.getCategoryPlot();
	p.setRangeGridlinePaint(Color.red);
        p.setRangeGridlinePaint(Color.YELLOW);

        jPReporte.add(new ChartPanel(jfc),BorderLayout.CENTER);
        jPReporte.updateUI();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Reportes dialog = new Reportes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPEscojerAnio;
    private javax.swing.JPanel jPReporte;
    // End of variables declaration//GEN-END:variables

}
