import javax.swing.JOptionPane;
import javax.swing.UIManager;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaPrincipal.java
 *
 * Created on 12-abr-2011, 13:30:12
 */

/**
 *
 * @author Administrador
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    public ConectorMySQL conectorMySql;
    public String usuario;
    public int filaTablaFactura = 0;
    public String contrasena = null;
    public String perfil = null;
//    public boolean bandera = true;
//    //BusquedaVentas busc = new BusquedaVentas(this.conectorMySql, venta.jTNombreProducto, venta.jTCodigo);
//    Thread hilo= null;

    public VentanaPrincipal() {
        try{
            //cargo MySQL portable
            //Process p1 = Runtime.getRuntime().exec("mysql/bin/mysqld.exe");
        }catch(Exception er){
            JOptionPane.showMessageDialog(this, "error cargando MySQL portable : "+er.toString());
        }

        initComponents();
        //run();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCentralContenido = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        panelSuperior = new javax.swing.JPanel();
        bUsuario = new javax.swing.JButton();
        bProductos = new javax.swing.JButton();
        bVentas = new javax.swing.JButton();
        panelInferior = new javax.swing.JPanel();
        bConsultas = new javax.swing.JButton();
        bConfiguracion = new javax.swing.JButton();
        bLogueo = new javax.swing.JButton();
        panelInferiorBarraEstado = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMUsuarios = new javax.swing.JMenu();
        jMCrearUsuario = new javax.swing.JMenuItem();
        jMLoguin = new javax.swing.JMenuItem();
        jMCambioSession = new javax.swing.JMenuItem();
        jMCerrarSession = new javax.swing.JMenuItem();
        jMProductos = new javax.swing.JMenu();
        jMCrearProductos = new javax.swing.JMenuItem();
        jMVentas = new javax.swing.JMenu();
        jMGenerarVenta = new javax.swing.JMenuItem();
        jMReportes = new javax.swing.JMenu();
        jMReportar = new javax.swing.JMenuItem();
        jMPanelConfiguracion = new javax.swing.JMenu();
        jMPanelConf = new javax.swing.JMenuItem();
        jMCerrar = new javax.swing.JMenu();
        iCerrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(811, 482));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelCentralContenido.setMaximumSize(new java.awt.Dimension(717, 200));
        panelCentralContenido.setMinimumSize(new java.awt.Dimension(717, 200));
        panelCentralContenido.setPreferredSize(new java.awt.Dimension(717, 200));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(103);
        jSplitPane1.setDividerSize(2);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        panelSuperior.setLayout(new java.awt.GridLayout(1, 0));

        bUsuario.setText("CREAR USUARIOS");
        bUsuario.setEnabled(false);
        bUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUsuarioActionPerformed(evt);
            }
        });
        panelSuperior.add(bUsuario);

        bProductos.setText("PRODUCTOS");
        bProductos.setEnabled(false);
        bProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProductosActionPerformed(evt);
            }
        });
        panelSuperior.add(bProductos);

        bVentas.setText("VENTAS");
        bVentas.setEnabled(false);
        bVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVentasActionPerformed(evt);
            }
        });
        panelSuperior.add(bVentas);

        jSplitPane1.setTopComponent(panelSuperior);

        panelInferior.setLayout(new java.awt.GridLayout(1, 0));

        bConsultas.setText("REPORTES");
        bConsultas.setEnabled(false);
        bConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsultasActionPerformed(evt);
            }
        });
        panelInferior.add(bConsultas);

        bConfiguracion.setText("PANEL CONFIGURACION");
        bConfiguracion.setEnabled(false);
        bConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConfiguracionActionPerformed(evt);
            }
        });
        panelInferior.add(bConfiguracion);

        bLogueo.setText("CAMBIAR SESSION");
        bLogueo.setEnabled(false);
        bLogueo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogueoActionPerformed(evt);
            }
        });
        panelInferior.add(bLogueo);

        jSplitPane1.setRightComponent(panelInferior);

        jPanel1.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout panelCentralContenidoLayout = new javax.swing.GroupLayout(panelCentralContenido);
        panelCentralContenido.setLayout(panelCentralContenidoLayout);
        panelCentralContenidoLayout.setHorizontalGroup(
            panelCentralContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentralContenidoLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        panelCentralContenidoLayout.setVerticalGroup(
            panelCentralContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentralContenidoLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        getContentPane().add(panelCentralContenido, java.awt.BorderLayout.CENTER);

        panelInferiorBarraEstado.setBackground(new java.awt.Color(255, 255, 255));
        panelInferiorBarraEstado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelInferiorBarraEstado.setMaximumSize(new java.awt.Dimension(0, 20));
        panelInferiorBarraEstado.setMinimumSize(new java.awt.Dimension(0, 20));
        panelInferiorBarraEstado.setPreferredSize(new java.awt.Dimension(0, 20));

        javax.swing.GroupLayout panelInferiorBarraEstadoLayout = new javax.swing.GroupLayout(panelInferiorBarraEstado);
        panelInferiorBarraEstado.setLayout(panelInferiorBarraEstadoLayout);
        panelInferiorBarraEstadoLayout.setHorizontalGroup(
            panelInferiorBarraEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 807, Short.MAX_VALUE)
        );
        panelInferiorBarraEstadoLayout.setVerticalGroup(
            panelInferiorBarraEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        getContentPane().add(panelInferiorBarraEstado, java.awt.BorderLayout.PAGE_END);

        jMUsuarios.setText("Usuarios");

        jMCrearUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMCrearUsuario.setText("Crear Usuario");
        jMCrearUsuario.setEnabled(false);
        jMCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCrearUsuarioActionPerformed(evt);
            }
        });
        jMUsuarios.add(jMCrearUsuario);

        jMLoguin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMLoguin.setText("Ingresar");
        jMLoguin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMLoguinActionPerformed(evt);
            }
        });
        jMUsuarios.add(jMLoguin);

        jMCambioSession.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMCambioSession.setText("Cambiar Session");
        jMCambioSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCambioSessionActionPerformed(evt);
            }
        });
        jMUsuarios.add(jMCambioSession);

        jMCerrarSession.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMCerrarSession.setText("Cerrar Session");
        jMCerrarSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCerrarSessionActionPerformed(evt);
            }
        });
        jMUsuarios.add(jMCerrarSession);

        jMenuBar1.add(jMUsuarios);

        jMProductos.setText("Productos");

        jMCrearProductos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMCrearProductos.setText("Productos");
        jMCrearProductos.setEnabled(false);
        jMCrearProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCrearProductosActionPerformed(evt);
            }
        });
        jMProductos.add(jMCrearProductos);

        jMenuBar1.add(jMProductos);

        jMVentas.setText("Ventas");

        jMGenerarVenta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMGenerarVenta.setText("Venta");
        jMGenerarVenta.setEnabled(false);
        jMGenerarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMGenerarVentaActionPerformed(evt);
            }
        });
        jMVentas.add(jMGenerarVenta);

        jMenuBar1.add(jMVentas);

        jMReportes.setText("Reportes");

        jMReportar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMReportar.setText("Mostrar Reporte");
        jMReportar.setEnabled(false);
        jMReportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMReportarActionPerformed(evt);
            }
        });
        jMReportes.add(jMReportar);

        jMenuBar1.add(jMReportes);

        jMPanelConfiguracion.setText("Panel De Configuracion");

        jMPanelConf.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMPanelConf.setText("Panel De Configuracion");
        jMPanelConf.setEnabled(false);
        jMPanelConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMPanelConfActionPerformed(evt);
            }
        });
        jMPanelConfiguracion.add(jMPanelConf);

        jMenuBar1.add(jMPanelConfiguracion);

        jMCerrar.setText("Cerrar");
        jMCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCerrarActionPerformed(evt);
            }
        });

        iCerrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        iCerrar.setText("Cerrar");
        iCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iCerrarActionPerformed(evt);
            }
        });
        jMCerrar.add(iCerrar);

        jMenuBar1.add(jMCerrar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUsuarioActionPerformed
        Usuarios ob = new Usuarios(this, false);
        Miscelania.centrarVentana(ob);
        ob.setVisible(true);
    }//GEN-LAST:event_bUsuarioActionPerformed

    private void jMCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCerrarActionPerformed
       try{
            Process p1 = Runtime.getRuntime().exec("TASKKILL /F /IM mysqld.exe /T");
        }catch(Exception er){
            JOptionPane.showMessageDialog(this, "error cerrando MySQL portable : "+er.toString());
        }
    }//GEN-LAST:event_jMCerrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            conectorMySql = new ConectorMySQL("127.0.0.1","ferreteria", "root", "");
            VentanaPrincipal.this.setSize(811, 482);
            Loguear ob = new Loguear(VentanaPrincipal.this, true);
            Miscelania.centrarVentana(ob);
            ob.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"<html>No hay <b>conexion con la Base De Datos</b><br>Por Favor Rectifique que el Cable de Red este Bien colocado y/o Reinicie el Equipo.<br>Si persiste el problema comuniquese con el <b>Desarrollador De Sistemas.</b></html>", "ERROR DE CONEXION..!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowOpened

    private void bVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVentasActionPerformed
        try{
            Factura ob = new Factura(this, true);
            Miscelania.centrarVentana(ob);
            ob.setVisible(true);
        }catch(Exception er){
            System.out.println("error en el boton de ventas : "+er.toString());
        }
    }//GEN-LAST:event_bVentasActionPerformed

    //inhabilito los botones
    public void inhabButton(){
        //inhabilito los botones
        bProductos.setEnabled(false);
        bVentas.setEnabled(false);
        bConsultas.setEnabled(false);
        bLogueo.setEnabled(false);
        //ahora los radioButton
        jMCrearProductos.setEnabled(false);
        jMGenerarVenta.setEnabled(false);
        jMReportar.setEnabled(false);
        jMCambioSession.setEnabled(false);
        bUsuario.setEnabled(false);
        bConfiguracion.setEnabled(false);
        //los radio
        jMCrearUsuario.setEnabled(false);
        jMPanelConf.setEnabled(false);
    }

    private void bLogueoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogueoActionPerformed
        Loguear o = new Loguear(this, true);
        Miscelania.centrarVentana(o);
        o.setVisible(true);
        inhabButton();
    }//GEN-LAST:event_bLogueoActionPerformed

    private void bProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProductosActionPerformed
        Productos obj = new Productos(VentanaPrincipal.this, true);
        Miscelania.centrarVentana(obj);
        System.out.println("voy a hacerlo visible..!");
        obj.setVisible(true);
    }//GEN-LAST:event_bProductosActionPerformed

    private void bConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsultasActionPerformed
        Reportes ob = new Reportes(VentanaPrincipal.this, true);
        Miscelania.centrarVentana(ob);
        ob.setVisible(true);
    }//GEN-LAST:event_bConsultasActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try{
            conectorMySql.conexion.close();
        }catch(Exception er){
            //JOptionPane.showMessageDialog(null, "error cerrando la conexion : "+er.toString());
        }
    }//GEN-LAST:event_formWindowClosing

    private void bConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConfiguracionActionPerformed
        PanelConfiguracion ob = new PanelConfiguracion(VentanaPrincipal.this, true);
        Miscelania.centrarVentana(ob);
        ob.setSize(581, 487);//581, 447
        ob.setVisible(true);
    }//GEN-LAST:event_bConfiguracionActionPerformed

    private void jMCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCrearUsuarioActionPerformed
        Usuarios ob = new Usuarios(VentanaPrincipal.this, true);
        Miscelania.centrarVentana(ob);
        ob.setVisible(true);
    }//GEN-LAST:event_jMCrearUsuarioActionPerformed

    private void jMLoguinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMLoguinActionPerformed
        Loguear ob = new Loguear(VentanaPrincipal.this, true);
        Miscelania.centrarVentana(ob);
        ob.setVisible(true);
    }//GEN-LAST:event_jMLoguinActionPerformed

    private void jMCrearProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCrearProductosActionPerformed
        Productos ob = new Productos(VentanaPrincipal.this, true);
        Miscelania.centrarVentana(ob);
        ob.setVisible(true);
    }//GEN-LAST:event_jMCrearProductosActionPerformed

    private void jMGenerarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMGenerarVentaActionPerformed
        Factura ob = new Factura(VentanaPrincipal.this, true);
        Miscelania.centrarVentana(ob);
        ob.setVisible(true);
    }//GEN-LAST:event_jMGenerarVentaActionPerformed

    private void jMReportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMReportarActionPerformed
        Reportes ob = new Reportes(VentanaPrincipal.this, true);
        Miscelania.centrarVentana(ob);
        ob.setVisible(true);
    }//GEN-LAST:event_jMReportarActionPerformed

    private void jMPanelConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMPanelConfActionPerformed
        PanelConfiguracion ob = new PanelConfiguracion(VentanaPrincipal.this, true);
        Miscelania.centrarVentana(ob);
        ob.setVisible(true);
    }//GEN-LAST:event_jMPanelConfActionPerformed

    private void iCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iCerrarActionPerformed
        VentanaPrincipal.this.dispose();
    }//GEN-LAST:event_iCerrarActionPerformed

    private void jMCambioSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCambioSessionActionPerformed
        Loguear o = new Loguear(VentanaPrincipal.this, true);
        Miscelania.centrarVentana(o);
        o.setVisible(true);
    }//GEN-LAST:event_jMCambioSessionActionPerformed

    private void jMCerrarSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCerrarSessionActionPerformed
        inhabButton();
    }//GEN-LAST:event_jMCerrarSessionActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //***
                try{
                    // bueno UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
                    // bueno UIManager.setLookAndFeel("de.muntjak.tinylookandfeel.TinyLookAndFeel");
                     // bueno UIManager.setLookAndFeel(new com.lipstikLF.LipstikLookAndFeel());
                    //vacile pero malo UIManager.setLookAndFeel("net.sourceforge.napkinlaf.NapkinLookAndFeel");
                    //mas o menos UIManager.setLookAndFeel("com.nilo.plaf.nimrod.NimRODLookAndFeel");
                    // malo UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                    // malo UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
                    // malo UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
                    // mas o menos pá malo UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
                    // malo UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
//  xxxxxxxxxxxxxxUIManager.setLookAndFeel("de.javasoft.plaf.synthetica.SyntheticaBlackMoonLookAndFeel");
                    // muy negro UIManager.setLookAndFeel("de.javasoft.plaf.synthetica.SyntheticaBlackStarLookAndFeel");
                    UIManager.setLookAndFeel("de.javasoft.plaf.synthetica.SyntheticaOrangeMetallicLookAndFeel");
               }catch(Exception er){

               }
                //***
                //new VentanaPrincipal().setVisible(true);
                VentanaPrincipal ob = new VentanaPrincipal();
                ob.setSize(717, 454);//ob.setSize(717, 424);
                Miscelania.centrarVentana(ob);
                ob.setVisible(true);

            }
        //}
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bConfiguracion;
    public javax.swing.JButton bConsultas;
    public javax.swing.JButton bLogueo;
    public javax.swing.JButton bProductos;
    public javax.swing.JButton bUsuario;
    public javax.swing.JButton bVentas;
    private javax.swing.JMenuItem iCerrar;
    public javax.swing.JMenuItem jMCambioSession;
    private javax.swing.JMenu jMCerrar;
    public javax.swing.JMenuItem jMCerrarSession;
    public javax.swing.JMenuItem jMCrearProductos;
    public javax.swing.JMenuItem jMCrearUsuario;
    public javax.swing.JMenuItem jMGenerarVenta;
    private javax.swing.JMenuItem jMLoguin;
    public javax.swing.JMenuItem jMPanelConf;
    private javax.swing.JMenu jMPanelConfiguracion;
    private javax.swing.JMenu jMProductos;
    public javax.swing.JMenuItem jMReportar;
    private javax.swing.JMenu jMReportes;
    private javax.swing.JMenu jMUsuarios;
    private javax.swing.JMenu jMVentas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel panelCentralContenido;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelInferiorBarraEstado;
    private javax.swing.JPanel panelSuperior;
    // End of variables declaration//GEN-END:variables

    public void start(){}
    
//    public void run(){
//        try{
//        System.out.println("el texto es : ");
//        Ventas venta = new Ventas(VentanaPrincipal.this, true);
//        BusquedaVentas busc = new BusquedaVentas(this.conectorMySql, venta.jTNombreProducto, venta.jTCodigo);
//        while(busc.isVisible()){
//        //while(bandera && hilo == null){
//
//                System.out.println("jgjgjkiuyuiu");
//                if(busc.isVisible()){
//                    System.out.println("jgjgjk");
//                    venta.jTNombreProducto.setText(busc.jTConsultas.getValueAt(busc.jTConsultas.getSelectedRow(), 1).toString());
//                    venta.jTCodigo.setText(busc.jTConsultas.getValueAt(busc.jTConsultas.getSelectedRow(), 0).toString());
//                    hilo.sleep(1000);
//                }
//
//        }
//    }catch(Exception er){
//                System.out.println("error con el hilo : "+er.toString());
//    }
//    }
}
